export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as GoodMatch } from './GoodMatch'
export { default as Testimonials } from './Testimonials'
export { default as Booking } from './Booking'
export { default as Footer } from './Footer'